# Main entrypoint of the workflow.
from datetime import datetime


start_time = datetime.now()
print(start_time)

# resources params
include : "rules/common.smk"

rule all:
	input:
		assembly = expand(["purge/{sample}/{sample}_polished_histogram.png"],
			 sample = ['G2402','AMADEUS','RAZ_044','TLP_030','DOR_476','SER_316','SIN_526','SMN_097'])

#include : "rules/read_correction.smk"
include : "rules/canu.smk"
include : "rules/polishing.smk"
include : "rules/purge_assembly.smk"
#include : "rules/annotation.smk"
#include : "rules/scaffolding.smk"


